version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-app
    ports:
      - "3000:3000"
    environment:
      - PORT=8080
      - NODE_ENV=development
      - ACCESS_TOKEN_SECRET="baNg"
      - REFRESH_TOKEN_SECRET="bAng"
      - CLOUDIARY_NAME='dpmnrmtdd'
      - API_KEY_CLOUDIARY='948551935874948'
      - API_SECRET_KEY_CLOUDIARY='WHoy1RaTiqTD-hRnr98Z1tSPOiE'
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ngovanbang
      MYSQL_DATABASE: e-commerce
      MYSQL_USER: root
      MYSQL_PASSWORD: ngovanbang
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
