export const ORDER_STATUS = {
  CREATED: "CREATED",
  PROCESSING: "PROCESSING",
  SHIPPED: "SHIPPED",
  DELIVERED: "DELIVERED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  RETURNED: "RETURNED",
}

export const ACCESS_TOKEN = 'access_token'

export const REFRESH_TOKEN = 'refresh_token'
